spring.application.name=detector
# Puerto donde correrá el backend
server.port=8080

# Configuración de conexión a PostgreSQL (Neon.tech)
spring.datasource.url=jdbc:postgresql://ep-noisy-pine-apct0js4.c-7.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_qckSQiyzW81O
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate (Consistencia y creación automática de tablas)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect