spring.application.name=detector
# Puerto donde correrá el backend
server.port=8080
SECRET_KEY = ServicioSeguroGenerarTokenSeguro12345
google.client.id=626481499479-gi7fsp4so1vqop36cs9sppjg4q3clhnm.apps.googleusercontent.com
pocketbase.url=http://127.0.0.1:8090
pocketbase.admin.email=elchuico@espe.edu.ec
pocketbase.admin.password=edith12345

# Configuración de conexión a PostgreSQL (Neon.tech)
spring.datasource.url=jdbc:postgresql://ep-noisy-pine-apct0js4.c-7.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_qckSQiyzW81O
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate (Consistencia y creación automática de tablas)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect